name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint --if-present || echo "No linting configured"
      continue-on-error: true
      
    - name: Run tests
      run: npm test --if-present || echo "No tests configured"
      continue-on-error: true
      
    - name: Test build process
      run: |
        npm run bundle
        echo "Build test completed successfully"
